### ISSUE TITLE
Telegram type within request body

### ISSUE THREAD

**Issue by NomeQ** [RideNoCo/drt-tds#26]
In our discussions, and in the original TDS spec, I recall the telegram type being part of the message, however, I don't see this reflected in the documentation here or on Swagger. 

**What we currently have**
message body:
```javascript
{
    tripTicketId: “123”,
    address: "",
    otherFields: "etc"
}
```

**What I believe we agreed on**
```javascript
{ tripRequest: {
    tripTicketId: “123”,
    address: "",
    otherFields: "etc"
} }
```

Do we have a consensus on how this should be? I am inclined toward the latter. It is better equipped to support future extensibility and error-checking. It will also allow for multiple telegrams to be sent in a single request if we ever want that ability.

**Comment by asiridissa** [comment]
Telegram type was part of the message when we had the one endpoint plan.
With multiple endpoints, one endpoint accepts only one telegram type. Since the endpoint know it's acceptable telegram type, do we need to use the type as the root property?

**Comment by asiridissa** [comment]
Multiple telegrams will lead to do multiple responses as well.
One trip request could be valid and one could be invalid. This will make the response complicated.
And sender should be ready to process that complicated responses and update their side accordingly.
I'd like if we don't support multiple telegrams at this stage to keep things simple.

**Comment by NomeQ** [comment]
@asiridissa yes I agree that we do not want to support multiple telegrams as part of this project.

But I think included telegram type in the spec adds no additional complexity at this point, and leads to the most flexibility in the future for other implementations. Since this is an update of a spec that is (hopefully) used in other cases, I think including telegram type leaves the most flexibility for future implementations outside this project.

**Comment by harshw** [comment]
Would prefer that the we keep with the spec as-is in swagger (ie...option 1 in Nomes message).

**Comment by keviniano** [comment]
I'm not sure what the process should be to reach consensus, but from our perspective going with Nome's option 2:

- Would add very little complexity to Spedsta and Ride Scheduler implementations
- Significantly reduces complexity for RideSheet, allowing it to continue to support its existing TDS implementations with the same codebase
- Adheres to the agreements we made at the meetings on this topic, as we understand them.

**Comment by asiridissa** [comment]
Since the early swagger version '0.2', it states that '**Request body for each endpoint is the schema of relevant telegram**' (https://app.swaggerhub.com/apis-docs/full-path/RideNoCo-TDS/0.2).
![image](https://github.com/RideNoCo/drt-tds/assets/3539388/55a36f16-5122-42cd-92c2-215ed78943f3)

This version illustrates both 
- Single endpoint with the telegram type / message type as a property 
(https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.2#/Single%20Endpoint/post_api_tds) and 
![image](https://github.com/RideNoCo/drt-tds/assets/3539388/869e2219-9bf8-4703-9389-021d99bcf086)
- Multiple endpoint example without telegram type mentioned in it.
(https://app.swaggerhub.com/apis/full-path/RideNoCo-TDS/0.2#/Multiple%20Endpoints/post_tripRequest)
![image](https://github.com/RideNoCo/drt-tds/assets/3539388/f923e696-4e0a-45f7-83a4-84128cc17941)

All the succeeding swagger versions follows the same pattern for multiple endpoints without the telegram type mentioned.

As per our understanding this is what we agreed and RideScheduler has followed the agreed pattern.

It is not a small task to add this change to our code base now.
To add the telegram type in the payload, we need to change 
- Receiving Endpoints, 
- Model Validations,
- Schema Validation process,
- Data mapping processes, 
- UI's,
- Telegram generation / sending  &
- Change all the Tests
in our code base.

Since we have multiple endpoints per each Telegram Type, the endpoint itself knows the expected telegram type for itself. 
Can Ridesheet alter the payload at the endpoint as per their requirement?

We can add Telegram Type as an HTTP Header with manageable effort, if it helps for Ridesheet.

**Comment by NomeQ** [comment]
Adding it as a header will not help us particularly. We will make the current spec work for us, and should have paid closer attention when that change occurred. It seems like the consensus to option A.
